Delete: Add tests, delete not needed plugins.
Add: plugin for testing
Group: all related commands to fiddling with files
Increase timeoutlen to 500 because command cP need to
be pressed really fast to work
Delete mappings for django they are not used anymore
Add
- mapping <leader>hf for showing only code that was changed to prev
commit
- mapping <leader>hh for highliting changes
- mapping <leader>h. for jump to next hunk
- mapping <leader>h, for jump to prev hunk
Change mapping <leader>bD to standart vim mapping
because is simply not working with which key plugin
Move mappings related to files in one place
Delete standart gutter(hunks) vim mappings - they were not working.
delete autocmnd! User line which key and leave only one that is calling
which_key#register by pressing leader key
Delete code that is no longer needed/used
And source .vimrc on every write without ! argument.

Bug: experienced at this version:

IOError: [Errno 4] Interrupted system cal

First time it showed up when I was adding janko-m/vim-test and dispatch
Plugin. But I think it can be related to which-key or dispatch.
But I remmember I think I can eliminate janko-m as cause.